### ISSUE TITLE
TransactionInfo{Cancel, Refund, Capture}: Merge?

### ISSUE THREAD

**Issue by cloveras** [vippsas/vipps-ecom-api#114]
These three are very similar, with the only difference being the `status` example and enum (all three have a `status` enum with one item btw):

* `TransactionInfoCancel`
* `TransactionInfoRefund`
* `TransactionInfoCapture`

Can we merge them into a common `TransactionInfo`? (`Transaction` is used for something else)

```
    TransactionInfoCancel:
      type: object
      required:
        - amount
        - status
        - timeStamp
        - transactionId
        - transactionText
      properties:
        amount:
          type: number
          format: double
          description: Ordered amount in øre
          example: 20000
        status:
          type: string
          enum:
            - Cancelled
          example: Cancelled
          description: >-
            Status which gives the current state of the payment within Vipps.
            See the [API
            guide](https://github.com/vippsas/vipps-ecom-api/blob/master/vipps-ecom-api.md#responses-from-requests)
            for more information.
        timeStamp:
          type: string
          description: Timestamp in ISO-8601 representing when the order was cancelled.
          example: '2018-12-12T11:18:38.246Z'
        transactionId:
          type: string
          description: Vipps transaction id
          example: '5001420062'
        transactionText:
          type: string
          description: Transaction text to be displayed in Vipps
          example: One pair of Vipps socks
          maxLength: 100
```
