### ISSUE TITLE
TransactionText's maxLength not specified for Capture, Refund, and Cancel actions

### ISSUE THREAD

**Issue by abraham-fox** [vippsas/vipps-ecom-api#64]
Hello! 
Thanks for great API documentation, but could you tell me what is the max length of **transactionText** for Capture, Refund, and Cancel actions?
Is it the same 100 chars as in the TransactionInfoInitiateDTO?
```
TransactionInfoInitiateDTO:
  ...
  transactionText:
          type: string
          description: Transaction text that can be displayed to end user
          maxLength: 100
          example: One pair of Vipps socks
```
